from turtle import Turtle, Screen
from race import Race
screen = Screen()
screen.setup(width=500,height=400)
turtle1 = Turtle()
turtle2 = Turtle()
turtle3 = Turtle()
turtle4 = Turtle()
turtle5 = Turtle()
turtle6 = Turtle()
turtles_list = [turtle1,turtle2,turtle3,turtle4,turtle5,turtle6]
screen = Screen()
screen.setup(width=500,height=400)
user_bet = screen.textinput(title="Make your bet",prompt="Which turtle is gonna win? ")
xyz = Race(turtles_list,user_bet)
x1 = Turtle()
x1.hideturtle()
x1.left(90)
x1.penup()
x1.goto(-210,-200)
x1.pendown()
x1.forward(400)
x2 = Turtle()
x2.hideturtle()
x2.left(90)
x2.penup()
x2.goto(240,-200)
x2.pendown()
x2.forward(400)
xyz.race()
screen.exitonclick()